export const TOTAL_TEAMS_2026 = 39

export interface DraftEntry {
  picks: number
  value: number
}

const draftData2026: Record<string, DraftEntry> = {
  "Gunnar Henderson": { picks: 20, value: 0.5 },
  "Ronald Acuna Jr.": { picks: 19, value: 0.53 },
  "Vladimir Guerrero Jr.": { picks: 18, value: 0.55 },
  "Austin Riley": { picks: 13, value: 0.68 },
  "Kyle Tucker": { picks: 10, value: 0.76 },
  "Luis Robert Jr.": { picks: 10, value: 0.76 },
  "Bobby Witt Jr.": { picks: 9, value: 0.79 },
  "Pete Alonso": { picks: 8, value: 0.82 },
  "Nick Kurtz": { picks: 8, value: 0.82 },
  "Francisco Alvarez": { picks: 7, value: 0.84 },
  "Jake Burger": { picks: 6, value: 0.87 },
  "Aaron Judge": { picks: 6, value: 0.87 },
  "Fernando Tatis Jr.": { picks: 6, value: 0.87 },
  "Juan Soto": { picks: 5, value: 0.89 },
  "Alex Bregman": { picks: 5, value: 0.89 },
  "Mookie Betts": { picks: 5, value: 0.89 },
  "Elly De La Cruz": { picks: 5, value: 0.89 },
  "Oneil Cruz": { picks: 5, value: 0.89 },
  "Tyler Soderstrom": { picks: 4, value: 0.92 },
  "Bo Bichette": { picks: 4, value: 0.92 },
  "Brent Rooker": { picks: 3, value: 0.95 },
  "Daulton Varsho": { picks: 3, value: 0.95 },
  "Vinnie Pasquantino": { picks: 3, value: 0.95 },
  "Adolis Garcia": { picks: 3, value: 0.95 },
  "Carlos Correa": { picks: 3, value: 0.95 },
  "Xander Bogaerts": { picks: 3, value: 0.95 },
  "Corey Seager": { picks: 2, value: 0.97 },
  "Jorge Soler": { picks: 2, value: 0.97 },
  "Ben Rice": { picks: 2, value: 0.97 },
  "Jackson Merrill": { picks: 2, value: 0.97 },
  "Zach Neto": { picks: 2, value: 0.97 },
  "Coby Mayo": { picks: 2, value: 0.97 },
  "Jazz Chisholm Jr.": { picks: 2, value: 0.97 },
  "Colson Montgomery": { picks: 2, value: 0.97 },
  "Jonathan Aranda": { picks: 2, value: 0.97 },
  "Salvador Perez": { picks: 2, value: 0.97 },
  "Rhys Hoskins": { picks: 2, value: 0.97 },
  "Julio Rodriguez": { picks: 2, value: 0.97 },
  "Matt Olson": { picks: 2, value: 0.97 },
  "Josh Naylor": { picks: 2, value: 0.97 },
  "Willi Castro": { picks: 2, value: 0.97 },
  "Nolan Arenado": { picks: 2, value: 0.97 },
  "Byron Buxton": { picks: 2, value: 0.97 },
  "Ryan O'Hearn": { picks: 2, value: 0.97 },
  "Andrew Vaughn": { picks: 1, value: 1 },
  "Paul Goldschmidt": { picks: 1, value: 1 },
  "Carlos Narvaez": { picks: 1, value: 1 },
  "Marcus Semien": { picks: 1, value: 1 },
  "Bryce Harper": { picks: 1, value: 1 },
  "Christopher Morel": { picks: 1, value: 1 },
  "James Wood": { picks: 1, value: 1 },
  "Mark Vientos": { picks: 1, value: 1 },
  "Dominic Canzone": { picks: 1, value: 1 },
  "Max Muncy": { picks: 1, value: 1 },
  "Wyatt Langford": { picks: 1, value: 1 },
  "Jasson Dominguez": { picks: 1, value: 1 },
  "Javier Baez": { picks: 1, value: 1 },
  "Miguel Andujar": { picks: 1, value: 1 },
  "Brett Baty": { picks: 1, value: 1 },
  "Nolan Gorman": { picks: 1, value: 1 },
  "Spencer Torkelson": { picks: 1, value: 1 },
  "Bo Naylor": { picks: 1, value: 1 },
  "Corbin Carroll": { picks: 1, value: 1 },
  "Jesus Sanchez": { picks: 1, value: 1 },
  "Spencer Steer": { picks: 1, value: 1 },
  "Manny Machado": { picks: 1, value: 1 },
  "Mike Trout": { picks: 1, value: 1 },
  "JJ Bleday": { picks: 1, value: 1 },
  "TJ Friedl": { picks: 1, value: 1 },
  "Willy Adames": { picks: 1, value: 1 },
  "Brenton Doyle": { picks: 1, value: 1 },
  "Noelvi Marte": { picks: 1, value: 1 },
  "Nolan Schanuel": { picks: 1, value: 1 },
  "Jackson Chourio": { picks: 1, value: 1 },
  "Pete Crow-Armstrong": { picks: 1, value: 1 },
  "Josh Smith": { picks: 1, value: 1 },
  "Kyle Stowers": { picks: 1, value: 1 },
  "Logan O'Hoppe": { picks: 1, value: 1 },
  "Marcell Ozuna": { picks: 1, value: 1 },
  "Steven Kwan": { picks: 1, value: 1 },
  "Anthony Volpe": { picks: 1, value: 1 },
  "Carson Kelly": { picks: 1, value: 1 },
  "Jarren Duran": { picks: 1, value: 1 },
  "Jose Ramirez": { picks: 1, value: 1 },
  "Miguel Vargas": { picks: 1, value: 1 },
  "Matt Wallner": { picks: 1, value: 1 },
  "Colton Cowser": { picks: 1, value: 1 },
  "Nathaniel Lowe": { picks: 1, value: 1 },
  "Colt Keith": { picks: 1, value: 1 },
  "Kyle Manzardo": { picks: 1, value: 1 },
}

export default draftData2026
