export default [
  'Aaron Hicks',
'Aaron Judge',
'Adalberto Mondesi',
'Alec Bohm',
'Alex Bregman',
'Anthony Rendon',
'Anthony Rizzo',
'Austin Meadows',
'Austin Riley',
'Bo Bichette',
'Brandon Belt',
'Brett Gardner',
'Bryce Harper',
'C.J. Cron',
'Carlos Correa',
'Charlie Blackmon',
'Christian Yelich',
'Clint Frazier',
'Cody Bellinger',
'Dominic Smith',
'Eugenio Suarez',
'Evan Longoria',
'Fernando Tatis Jr.',
'Francisco Lindor',
'Franmil Reyes',
'Giancarlo Stanton',
'Gio Urshela',
'Gregory Polanco',
'J.D. Davis',
'J.D. Martinez',
'James McCann',
'Joc Pederson',
'Joey Gallo',
'Jorge Soler',
'Jose Abreu',
'Josh Bell',
'Josh Donaldson',
'Juan Soto',
'Justin Turner',
'Kris Bryant',
'Manny Machado',
'Matt Kemp',
'Matt Olson',
'Michael Conforto',
'Miguel Sano',
'Mike Moustakas',
'Mike Trout',
'Nelson Cruz',
'Nick Castellanos',
'Nolan Arenado',
'Ozzie Albies',
'Paul Goldschmidt',
'Pete Alonso',
'Randy Arozarena',
'Rhys Hoskins',
'Ronald Acuna Jr.',
'Ryan Mountcastle',
'Shohei Ohtani',
'Trevor Story',
'Ty France',
'Vladimir Guerrero Jr.',

]