import type { Teams } from '../types'

const teams: Teams = {
  "Andrew Asdahl": [
    "Andrew Vaughn",
    "Austin Riley",
    "Francisco Alvarez",
    "Juan Soto",
    "Paul Goldschmidt",
    "Pete Alonso",
    "Ronald Acuna Jr.",
  ],
  "Anthony Timpanaro": [
    "Austin Riley",
    "Brent Rooker",
    "Daulton Varsho",
    "Gunnar Henderson",
    "Kyle Tucker",
    "Ronald Acuna Jr.",
    "Vladimir Guerrero Jr.",
  ],
  "Billy Carlo": [
    "Alex Bregman",
    "Austin Riley",
    "Gunnar Henderson",
    "Juan Soto",
    "Kyle Tucker",
    "Luis Robert Jr.",
    "Vladimir Guerrero Jr.",
  ],
  "Billy Watts": [
    "Carlos Narvaez",
    "Corey Seager",
    "Marcus Semien",
    "Mookie Betts",
    "Pete Alonso",
    "Ronald Acuna Jr.",
    "Vladimir Guerrero Jr.",
  ],
  "Brett Jimenez": [
    "Alex Bregman",
    "Elly De La Cruz",
    "Gunnar Henderson",
    "Oneil Cruz",
    "Ronald Acuna Jr.",
    "Vinnie Pasquantino",
    "Vladimir Guerrero Jr.",
  ],
  "Campy": [
    "Bryce Harper",
    "Francisco Alvarez",
    "Gunnar Henderson",
    "Jake Burger",
    "Juan Soto",
    "Luis Robert Jr.",
    "Ronald Acuna Jr.",
  ],
  "Chris Towler 1": [
    "Austin Riley",
    "Bobby Witt Jr.",
    "Brent Rooker",
    "Gunnar Henderson",
    "Kyle Tucker",
    "Ronald Acuna Jr.",
    "Vladimir Guerrero Jr.",
  ],
  "Chris Towler 2": [
    "Adolis Garcia",
    "Alex Bregman",
    "Jake Burger",
    "Jorge Soler",
    "Luis Robert Jr.",
    "Nick Kurtz",
    "Pete Alonso",
  ],
  "Collin Stiles": [
    "Ben Rice",
    "Gunnar Henderson",
    "Jackson Merrill",
    "Kyle Tucker",
    "Luis Robert Jr.",
    "Tyler Soderstrom",
    "Vinnie Pasquantino",
  ],
  "Dan O'Leary": [
    "Christopher Morel",
    "James Wood",
    "Luis Robert Jr.",
    "Mark Vientos",
    "Oneil Cruz",
    "Vinnie Pasquantino",
    "Zach Neto",
  ],
  "Dan Pasacrita": [
    "Austin Riley",
    "Francisco Alvarez",
    "Jake Burger",
    "Juan Soto",
    "Kyle Tucker",
    "Ronald Acuna Jr.",
    "Vladimir Guerrero Jr.",
  ],
  "Dave Trompeter 1": [
    "Bobby Witt Jr.",
    "Coby Mayo",
    "Daulton Varsho",
    "Gunnar Henderson",
    "Jazz Chisholm Jr.",
    "Tyler Soderstrom",
    "Zach Neto",
  ],
  "Dave Trompeter 2": [
    "Colson Montgomery",
    "Dominic Canzone",
    "Jonathan Aranda",
    "Max Muncy",
    "Nick Kurtz",
    "Salvador Perez",
    "Wyatt Langford",
  ],
  "Dom Dicerbo": [
    "Austin Riley",
    "Bobby Witt Jr.",
    "Francisco Alvarez",
    "Gunnar Henderson",
    "Nick Kurtz",
    "Ronald Acuna Jr.",
    "Vladimir Guerrero Jr.",
  ],
  "Fred": [
    "Aaron Judge",
    "Carlos Correa",
    "Gunnar Henderson",
    "Jonathan Aranda",
    "Rhys Hoskins",
    "Ronald Acuna Jr.",
    "Vladimir Guerrero Jr.",
  ],
  "Gabe": [
    "Aaron Judge",
    "Carlos Correa",
    "Jasson Dominguez",
    "Javier Baez",
    "Juan Soto",
    "Miguel Andujar",
    "Xander Bogaerts",
  ],
  "Greg Schaefer 1": [
    "Adolis Garcia",
    "Bobby Witt Jr.",
    "Brent Rooker",
    "Corey Seager",
    "Daulton Varsho",
    "Gunnar Henderson",
    "Vladimir Guerrero Jr.",
  ],
  "Greg Schaefer 2": [
    "Austin Riley",
    "Fernando Tatis Jr.",
    "Gunnar Henderson",
    "Jake Burger",
    "Kyle Tucker",
    "Nick Kurtz",
    "Ronald Acuna Jr.",
  ],
  "Harrison Uzwy": [
    "Austin Riley",
    "Ben Rice",
    "Francisco Alvarez",
    "Gunnar Henderson",
    "Kyle Tucker",
    "Pete Alonso",
    "Vladimir Guerrero Jr.",
  ],
  "Hertling": [
    "Aaron Judge",
    "Brett Baty",
    "Coby Mayo",
    "Elly De La Cruz",
    "Francisco Alvarez",
    "Gunnar Henderson",
    "Ronald Acuna Jr.",
  ],
  "Jason Myones": [
    "Fernando Tatis Jr.",
    "Gunnar Henderson",
    "Julio Rodriguez",
    "Luis Robert Jr.",
    "Nolan Gorman",
    "Oneil Cruz",
    "Spencer Torkelson",
  ],
  "Jeremy Tamayo": [
    "Bo Naylor",
    "Bobby Witt Jr.",
    "Corbin Carroll",
    "Jesus Sanchez",
    "Mookie Betts",
    "Salvador Perez",
    "Spencer Steer",
  ],
  "Keith McLoat Jr.": [
    "Bobby Witt Jr.",
    "Fernando Tatis Jr.",
    "Jorge Soler",
    "Matt Olson",
    "Mookie Betts",
    "Ronald Acuna Jr.",
    "Vladimir Guerrero Jr.",
  ],
  "Keith Mcloat Sr.": [
    "Bo Bichette",
    "Fernando Tatis Jr.",
    "Manny Machado",
    "Mike Trout",
    "Rhys Hoskins",
    "Ronald Acuna Jr.",
    "Vladimir Guerrero Jr.",
  ],
  "Kevin Cavalcante": [
    "Austin Riley",
    "Bobby Witt Jr.",
    "Gunnar Henderson",
    "Jake Burger",
    "Kyle Tucker",
    "Nick Kurtz",
    "Ronald Acuna Jr.",
  ],
  "Kevin Towler": [
    "Aaron Judge",
    "JJ Bleday",
    "Josh Naylor",
    "TJ Friedl",
    "Willi Castro",
    "Willy Adames",
    "Xander Bogaerts",
  ],
  "Kyle Barth": [
    "Austin Riley",
    "Bobby Witt Jr.",
    "Elly De La Cruz",
    "Gunnar Henderson",
    "Kyle Tucker",
    "Matt Olson",
    "Vladimir Guerrero Jr.",
  ],
  "Lou 1": [
    "Adolis Garcia",
    "Elly De La Cruz",
    "Gunnar Henderson",
    "Luis Robert Jr.",
    "Oneil Cruz",
    "Pete Alonso",
    "Vladimir Guerrero Jr.",
  ],
  "Lou 2": [
    "Aaron Judge",
    "Brenton Doyle",
    "Fernando Tatis Jr.",
    "Noelvi Marte",
    "Nolan Schanuel",
    "Ronald Acuna Jr.",
    "Willi Castro",
  ],
  "Michael Bignami II": [
    "Austin Riley",
    "Fernando Tatis Jr.",
    "Jackson Chourio",
    "Kyle Tucker",
    "Luis Robert Jr.",
    "Ronald Acuna Jr.",
    "Tyler Soderstrom",
  ],
  "Michael Cafarella": [
    "Bo Bichette",
    "Elly De La Cruz",
    "Francisco Alvarez",
    "Luis Robert Jr.",
    "Nick Kurtz",
    "Oneil Cruz",
    "Pete Crow-Armstrong",
  ],
  "Michael Egolf": [
    "Aaron Judge",
    "Josh Smith",
    "Luis Robert Jr.",
    "Mookie Betts",
    "Nolan Arenado",
    "Ronald Acuna Jr.",
    "Vladimir Guerrero Jr.",
  ],
  "Mike Fisch": [
    "Byron Buxton",
    "Kyle Stowers",
    "Logan O'Hoppe",
    "Marcell Ozuna",
    "Ryan O'Hearn",
    "Steven Kwan",
    "Tyler Soderstrom",
  ],
  "Pedy": [
    "Bobby Witt Jr.",
    "Gunnar Henderson",
    "Mookie Betts",
    "Nick Kurtz",
    "Nolan Arenado",
    "Ronald Acuna Jr.",
    "Vladimir Guerrero Jr.",
  ],
  "Rob Cacace": [
    "Anthony Volpe",
    "Byron Buxton",
    "Carson Kelly",
    "Jarren Duran",
    "Jose Ramirez",
    "Miguel Vargas",
    "Ryan O'Hearn",
  ],
  "Saul": [
    "Austin Riley",
    "Gunnar Henderson",
    "Jake Burger",
    "Matt Wallner",
    "Pete Alonso",
    "Ronald Acuna Jr.",
    "Vladimir Guerrero Jr.",
  ],
  "Scott Backer": [
    "Alex Bregman",
    "Bo Bichette",
    "Colton Cowser",
    "Gunnar Henderson",
    "Jackson Merrill",
    "Jazz Chisholm Jr.",
    "Nick Kurtz",
  ],
  "Stephen Burns": [
    "Alex Bregman",
    "Carlos Correa",
    "Julio Rodriguez",
    "Nathaniel Lowe",
    "Pete Alonso",
    "Vladimir Guerrero Jr.",
    "Xander Bogaerts",
  ],
  "Val": [
    "Austin Riley",
    "Bo Bichette",
    "Colson Montgomery",
    "Colt Keith",
    "Josh Naylor",
    "Kyle Manzardo",
    "Pete Alonso",
  ],
}

export default teams
