export default [
  'Andrew;Corey Seager',
  'Andrew;Didi Gregorius',
  'Andrew;Dominic Smith',
  'Andrew;Giancarlo Stanton',
  'Andrew;Kris Bryant',
  'Andrew;Pete Alonso',
  'Andrew;Ryan McMahon',
  'Anthony Minucci;Alex Bregman',
  'Anthony Minucci;George Springer',
  'Anthony Minucci;Juan Soto',
  'Anthony Minucci;Luke Voit',
  'Anthony Minucci;Ronald Acuna Jr.',
  'Anthony Minucci;Starling Marte',
  'Anthony Minucci;Vladimir Guerrero Jr.',
  'Anthony T;Bryce Harper',
  'Anthony T;Byron Buxton',
  'Anthony T;George Springer',
  'Anthony T;Luis Robert',
  'Anthony T;Luke Voit',
  'Anthony T;Pete Alonso',
  'Anthony T;Ronald Acuna Jr.',
  'Billy;Anthony Santander',
  'Billy;Brendan Rodgers',
  'Billy;Bryce Harper',
  'Billy;Corey Seager',
  'Billy;Jesus Sanchez',
  'Billy;Matt Olson',
  'Billy;Ronald Acuna Jr.',
  'Chris Persad;Byron Buxton',
  'Chris Persad;Francisco Lindor',
  'Chris Persad;Kris Bryant',
  'Chris Persad;Kyle Schwarber',
  'Chris Persad;Luis Robert',
  'Chris Persad;Rhys Hoskins',
  'Chris Persad;Ronald Acuna Jr.',
  'Chris Towler;Gavin Sheets',
  'Chris Towler;Juan Soto',
  'Chris Towler;Luke Voit',
  'Chris Towler;Pete Alonso',
  'Chris Towler;Ronald Acuna Jr.',
  'Chris Towler;Sam Hilliard',
  'Chris Towler;Tyler O\'Neill',
  'Collin;Corey Seager',
  'Collin;George Springer',
  'Collin;Jazz Chisholm Jr.',
  'Collin;Juan Soto',
  'Collin;Luis Robert',
  'Collin;Matt Olson',
  'Collin;Ronald Acuna Jr.',
  'Dan Delia;Eric Hosmer',
  'Dan Delia;Francisco Lindor',
  'Dan Delia;Freddie Freeman',
  'Dan Delia;Michael Conforto',
  'Dan Delia;Ronald Acuna Jr.',
  'Dan Delia;Shohei Ohtani',
  'Dan Delia;Yoan Moncada',
  'Dan O\'Leary;Alex Bregman',
  'Dan O\'Leary;Dominic Smith',
  'Dan O\'Leary;Jesse Winker',
  'Dan O\'Leary;Joc Pederson',
  'Dan O\'Leary;Matt Chapman',
  'Dan O\'Leary;Trey Mancini',
  'Dan O\'Leary;Vladimir Guerrero Jr.',
  'Dan Pasacrita;George Springer',
  'Dan Pasacrita;Jarred Kelenic',
  'Dan Pasacrita;Luis Robert',
  'Dan Pasacrita;Luke Voit',
  'Dan Pasacrita;Rhys Hoskins',
  'Dan Pasacrita;Ronald Acuna Jr.',
  'Dan Pasacrita;Shohei Ohtani',
  'Dave 1;Byron Buxton',
  'Dave 1;George Springer',
  'Dave 1;Jesus Sanchez',
  'Dave 1;Kyle Schwarber',
  'Dave 1;Luis Robert',
  'Dave 1;Pete Alonso',
  'Dave 1;Ronald Acuna Jr.',
  'Dave 2;Bobby Dalbec',
  'Dave 2;Corey Seager',
  'Dave 2;Dylan Carlson',
  'Dave 2;Jarred Kelenic',
  'Dave 2;Matt Chapman',
  'Dave 2;Rhys Hoskins',
  'Dave 2;Yordan Alvarez',
  'Fred;Aaron Judge',
  'Fred;Alex Bregman',
  'Fred;Jarred Kelenic',
  'Fred;Luis Robert',
  'Fred;Luke Voit',
  'Fred;Mookie Betts',
  'Fred;Vladimir Guerrero Jr.',
  'Harrison;Franmil Reyes',
  'Harrison;George Springer',
  'Harrison;Giancarlo Stanton',
  'Harrison;Kris Bryant',
  'Harrison;Luis Robert',
  'Harrison;Luke Voit',
  'Harrison;Ronald Acuna Jr.',
  'Hertling;Brendan Rodgers',
  'Hertling;Bryce Harper',
  'Hertling;George Springer',
  'Hertling;Juan Soto',
  'Hertling;Kris Bryant',
  'Hertling;Luke Voit',
  'Hertling;Ronald Acuna Jr.',
  'Jessica;Amed Rosario',
  'Jessica;Brad Miller',
  'Jessica;Bryce Harper',
  'Jessica;Lourdes Gurriel Jr.',
  'Jessica;Luke Voit',
  'Jessica;Vladimir Guerrero Jr.',
  'Jessica;Yuli Gurriel',
  'Keith;Byron Buxton',
  'Keith;Corey Seager',
  'Keith;Franmil Reyes',
  'Keith;George Springer',
  'Keith;Luis Robert',
  'Keith;Mookie Betts',
  'Keith;Pete Alonso',
  'Keith Sr.;Anthony Rizzo',
  'Keith Sr.;Juan Soto',
  'Keith Sr.;Kyle Schwarber',
  'Keith Sr.;Luke Voit',
  'Keith Sr.;Michael Conforto',
  'Keith Sr.;Rhys Hoskins',
  'Keith Sr.;Ronald Acuna Jr.',
  'Kevin Cavalcante;Alex Bregman',
  'Kevin Cavalcante;Bobby Bradley',
  'Kevin Cavalcante;Kyle Schwarber',
  'Kevin Cavalcante;Luis Robert',
  'Kevin Cavalcante;Luke Voit',
  'Kevin Cavalcante;Matt Olson',
  'Kevin Cavalcante;Pete Alonso',
  'Kyle Ansbach;Alex Bregman',
  'Kyle Ansbach;Byron Buxton',
  'Kyle Ansbach;Corey Seager',
  'Kyle Ansbach;George Springer',
  'Kyle Ansbach;Juan Soto',
  'Kyle Ansbach;Luis Robert',
  'Kyle Ansbach;Vladimir Guerrero Jr.',
  'Lou 1;Alex Bregman',
  'Lou 1;Corey Seager',
  'Lou 1;Giancarlo Stanton',
  'Lou 1;Kris Bryant',
  'Lou 1;Luis Robert',
  'Lou 1;Luke Voit',
  'Lou 1;Vladimir Guerrero Jr.',
  'Lou 2;Alex Bregman',
  'Lou 2;Andrew Vaughn',
  'Lou 2;Bryce Harper',
  'Lou 2;Josh Donaldson',
  'Lou 2;Juan Soto',
  'Lou 2;Rowdy Tellez',
  'Lou 2;Ryan Mountcastle',
  'Matt Campanile;Anthony Rizzo',
  'Matt Campanile;Carlos Correa',
  'Matt Campanile;Dominic Smith',
  'Matt Campanile;Juan Soto',
  'Matt Campanile;Kris Bryant',
  'Matt Campanile;Luke Voit',
  'Matt Campanile;Pete Alonso',
  'Pedy;Anthony Rizzo',
  'Pedy;Corey Seager',
  'Pedy;Juan Soto',
  'Pedy;Kris Bryant',
  'Pedy;Luis Robert',
  'Pedy;Mookie Betts',
  'Pedy;Paul Goldschmidt',
  'Perry;Byron Buxton',
  'Perry;Corey Seager',
  'Perry;Jarred Kelenic',
  'Perry;Luis Robert',
  'Perry;Manny Machado',
  'Perry;Mookie Betts',
  'Perry;Vladimir Guerrero Jr.',
  'Rob Bianco;Anthony Rizzo',
  'Rob Bianco;Byron Buxton',
  'Rob Bianco;Kyle Schwarber',
  'Rob Bianco;Mookie Betts',
  'Rob Bianco;Randal Grichuk',
  'Rob Bianco;Ronald Acuna Jr.',
  'Rob Bianco;Rougned Odor',
  'Sam Clement;Aaron Judge',
  'Sam Clement;Byron Buxton',
  'Sam Clement;Jazz Chisholm Jr.',
  'Sam Clement;Juan Soto',
  'Sam Clement;Luis Robert',
  'Sam Clement;Ronald Acuna Jr.',
  'Sam Clement;Tyrone Taylor',
  'Saul;A.J. Pollock',
  'Saul;Alex Bregman',
  'Saul;Bo Bichette',
  'Saul;Corey Seager',
  'Saul;George Springer',
  'Saul;Juan Soto',
  'Saul;Teoscar Hernandez',
  'Scott;Carlos Correa',
  'Scott;George Springer',
  'Scott;Jesus Sanchez',
  'Scott;Juan Soto',
  'Scott;Kyle Schwarber',
  'Scott;Luis Robert',
  'Scott;Ronald Acuna Jr.',
  'Spencer;Charlie Blackmon',
  'Spencer;Joc Pederson',
  'Spencer;Jose Altuve',
  'Spencer;Justin Upton',
  'Spencer;Kyle Schwarber',
  'Spencer;Trevor Story',
  'Spencer;Yuli Gurriel',
  'Stephen Burns;Alex Bregman',
  'Stephen Burns;Anthony Rizzo',
  'Stephen Burns;Gary Sanchez',
  'Stephen Burns;George Springer',
  'Stephen Burns;Joey Gallo',
  'Stephen Burns;Kyle Schwarber',
  'Stephen Burns;Luke Voit',
  'Travis Uzwy;Corey Seager',
  'Travis Uzwy;Gary Sanchez',
  'Travis Uzwy;Jeimer Candelario',
  'Travis Uzwy;Kevin Pillar',
  'Travis Uzwy;Shohei Ohtani',
  'Travis Uzwy;Trevor Story',
  'Travis Uzwy;Trey Mancini',
].reduce((accum, str) => {
  const [captain, player] = str.split(';')
      if (!accum[captain]) {
        accum[captain] = []
      }
      accum[captain].push(player)
      return accum
}, {})